using System.Collections.Immutable;
using System.Text;
using Lunitium.DependencyInjection.Enums;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Lunitium.DependencyInjection;

[Generator]
public class DependencyGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var valueProvider = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: Filter,
                transform: ParseData
            )
            .Where(static service => service is not null)
            .Collect();
        
        context.RegisterSourceOutput(valueProvider, Generate);
    }

    private static bool Filter(SyntaxNode node, CancellationToken cancellationToken)
    {
        return node is ClassDeclarationSyntax { AttributeLists.Count: > 0 };
    }

    private static ServiceToRegister? ParseData(GeneratorSyntaxContext context, CancellationToken cancellationToken)
    {
        var node = (ClassDeclarationSyntax)context.Node;
        
        if (context.SemanticModel.GetDeclaredSymbol(node, cancellationToken) is not INamedTypeSymbol classSymbol)
            return null;
        
        foreach (var attributeData in classSymbol.GetAttributes())
        {
            if (attributeData.AttributeClass?.Name != "DependencyAttribute")
                continue;

            ITypeSymbol? interfaceType = null;
            
            if (attributeData.AttributeClass.IsGenericType)
            {
                interfaceType = attributeData.AttributeClass.TypeArguments.FirstOrDefault();
            }

            var selfClass = classSymbol.ToDisplayString();
            var lifeTimeValue = (int?)attributeData.ConstructorArguments.FirstOrDefault().Value;

            return new ServiceToRegister()
            {
                Name = selfClass,
                LifeTime = lifeTimeValue is null ? LifeTime.Scoped : (LifeTime)lifeTimeValue,
                InterfaceName = interfaceType?.ToDisplayString()
            };
        }
        
        return null;
    }

    private static void Generate(SourceProductionContext context, ImmutableArray<ServiceToRegister?> services)
    {
        var result = GenerateExtensionClass(services);
        
        context.AddSource("DependencyInjection.g.cs", SourceText.From(result, Encoding.UTF8));
    }
    
    private static string GenerateExtensionClass(ImmutableArray<ServiceToRegister?> services)
    {
        var sb = new StringBuilder(2048);

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();
        sb.AppendLine("namespace Lunitium.DependencyInjection;");
        sb.AppendLine();
        sb.AppendLine("public static class DependencyInjectionExtensions");
        sb.AppendLine("{");
        sb.AppendLine("    public static IServiceCollection AddLunitiumDependencies(this IServiceCollection services)");
        sb.AppendLine("    {");

        foreach (var service in services)
        {
            if (service == null) continue;

            var method = service.LifeTime switch
            {
                LifeTime.Singleton => "AddSingleton",
                LifeTime.Transient => "AddTransient",
                _ => "AddScoped"
            };

            sb.AppendLine(!string.IsNullOrEmpty(service.InterfaceName)
                ? $"        services.{method}<{service.InterfaceName}, {service.Name}>();"
                : $"        services.{method}<{service.Name}>();");
        }

        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}