using System.Text;
using Lunitium.Mapper.Generator.Analysis;
using Lunitium.Mapper.Generator.Enums;
using Lunitium.Mapper.Generator.Models;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Lunitium.Mapper.Generator.Templates;

public class MapperDtoRecordTemplate(SourceProductionContext context, MapperToRegister mapper)
{
    public string Render()
    {
        var sb = new StringBuilder(2048);

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine();
        sb.AppendLine($"namespace {mapper.Namespace};");
        sb.AppendLine();
        sb.AppendLine($"public partial class {mapper.ModelSymbol.Name}");
        sb.AppendLine("{");

        if (mapper.MapDirection.HasFlag(MapDirection.ToDto))
        {
            sb.AppendLine(RenderToDto());
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

    private string RenderToDto()
    {
        return
            $$"""
                  public {{mapper.DtoSymbol.ToDisplayString()}} ToDto()
                  {
                      return new {{mapper.DtoSymbol.ToDisplayString()}}(
                          {{RenderDtoCtor()}}
                      );
                  }
              """;
    }

    private string RenderDtoCtor()
    {
        var ctorProps = GetConstructorProps(mapper.DtoSymbol);
        var parameters = new List<string>();

        foreach (var ctorProp in ctorProps)
        {
            var prop = mapper.Props.FirstOrDefault(x => x.Key == ctorProp.Name);
            var symbol = prop.Value.ModelProp;

            if (symbol != null)
            {
                var conversion = prop.Value.ModelToDto;

                if (conversion is { Exists: false })
                {
                    context.ReportDiagnostic(Diagnostic.Create(
                        AnalysisError.DontMatchType,
                        mapper.AttributeSymbol.GetLocation(),
                        symbol.Name,
                        ctorProp.Type.ToDisplayString()
                    ));
                    continue;
                }

                if (ctorProp.Type.NullableAnnotation == NullableAnnotation.NotAnnotated &&
                    symbol.Type.NullableAnnotation == NullableAnnotation.Annotated)
                {
                    context.ReportDiagnostic(Diagnostic.Create(
                        AnalysisError.NullableMismatch,
                        mapper.AttributeSymbol.GetLocation(),
                        symbol.Name,
                        ctorProp.Type.ToDisplayString()
                    ));
                }

                if (conversion is { IsExplicit: true })
                {
                    parameters.Add($"({ctorProp.Type.ToDisplayString()})this.{symbol.Name}");
                    continue;
                }

                parameters.Add($"this.{symbol.Name}");
                continue;
            }

            if (ctorProp.HasExplicitDefaultValue)
            {
                var parameterSyntax =
                    ctorProp.DeclaringSyntaxReferences.FirstOrDefault()?.GetSyntax() as ParameterSyntax;

                parameters.Add($"{parameterSyntax?.Default?.Value.ToString()}");
                continue;
            }

            context.ReportDiagnostic(Diagnostic.Create(
                AnalysisError.ModelDontHaveThisProp,
                mapper.AttributeSymbol.GetLocation(),
                mapper.ModelSymbol.Name,
                ctorProp.Name
            ));
        }

        return string.Join(", ", parameters);
    }

    private static List<IParameterSymbol> GetConstructorProps(INamedTypeSymbol classSymbol)
    {
        if (!classSymbol.IsRecord)
            return [];

        var ctor = classSymbol.Constructors.FirstOrDefault(x =>
            x.DeclaringSyntaxReferences.Any(s => s.GetSyntax() is RecordDeclarationSyntax));

        return ctor == null ? [] : ctor.Parameters.ToList();
    }
}