using System.Text;
using Lunitium.Mapper.Generator.Enums;
using Lunitium.Mapper.Generator.Models;
using Microsoft.CodeAnalysis;

namespace Lunitium.Mapper.Generator.Templates;

public class MapperTemplate(SourceProductionContext context, MapperInfos mapper)
{
    public string Render()
    {
        var sb = new StringBuilder(2048);

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {mapper.Namespace};");
        sb.AppendLine();
        sb.AppendLine($"public partial class {mapper.ModelName}");
        sb.AppendLine("{");

        foreach (var mapperInfo in mapper.Infos)
        {
            if (mapperInfo.MapAction.HasFlag(MapAction.To))
            {
                var template = new MapperToTemplate(context, mapperInfo);
                sb.AppendLine(template.Render());
            }

            if (mapperInfo.MapAction.HasFlag(MapAction.From))
            {
                var template = new MapperFromTemplate(context, mapperInfo);
                sb.AppendLine(template.Render());
            }
        }

        sb.AppendLine("}");

        return sb.ToString();
    }
}