using System.Text;
using Lunitium.Mapper.Generator.Models;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Lunitium.Mapper.Generator.Templates;

public class MapperDtoRecordTemplate(MapperToRegister mapper)
{
    public string Render()
    {
        var sb = new StringBuilder(2048);

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine();
        sb.AppendLine($"namespace {mapper.Namespace};");
        sb.AppendLine();
        sb.AppendLine($"public partial class {mapper.ModelSymbol.Name}");
        sb.AppendLine("{");
        sb.AppendLine(RenderToDto());
        sb.AppendLine("}");

        return sb.ToString();
    }

    private string RenderToDto()
    {
        var ctorProps = GetRecordConstructorProps(mapper.DtoProps);

        return
            $$"""
                  public {{mapper.DtoSymbol.ToDisplayString()}} ToDto()
                  {
                      return new {{mapper.DtoSymbol.ToDisplayString()}}(
                          {{RenderCtorParameters(ctorProps, mapper.ModelProps)}}
                      );
                  }
              """;
    }

    private static string RenderCtorParameters(List<IParameterSymbol> ctorProps, List<IPropertySymbol> props)
    {
        var parameters = new List<string>();

        foreach (var ctorProp in ctorProps)
        {
            var symbol = props.FirstOrDefault(x =>
                x.Name == ctorProp.Name &&
                SymbolEqualityComparer.Default.Equals(x.Type, ctorProp.Type));

            if (symbol != null)
            {
                parameters.Add($"this.{symbol.Name}");
            }
            
            if (ctorProp.HasExplicitDefaultValue)
            {
                var parameterSyntax = ctorProp.DeclaringSyntaxReferences.FirstOrDefault()?.GetSyntax() as ParameterSyntax;
                
                parameters.Add($"{parameterSyntax?.Default?.Value.ToString()}");
            }
            
            continue;
        }
        
        return string.Join(", ", parameters);
    }

    private static List<IParameterSymbol> GetRecordConstructorProps(List<IPropertySymbol> props)
    {
        if (props.Count == 0)
            return [];

        var recordSymbol = props[0].ContainingType;

        if (!recordSymbol.IsRecord)
            return [];

        var ctor = recordSymbol.Constructors.FirstOrDefault(x =>
            x.DeclaringSyntaxReferences.Any(s => s.GetSyntax() is RecordDeclarationSyntax));

        return ctor == null ? [] : ctor.Parameters.ToList();
    }
}